# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Choice_1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Choice_1.setGeometry(QtCore.QRect(120, 230, 121, 17))
        self.Choice_1.setObjectName("Choice_1")
        self.Choice_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Choice_2.setGeometry(QtCore.QRect(120, 310, 121, 17))
        self.Choice_2.setObjectName("Choice_2")
        self.Choice_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Choice_3.setGeometry(QtCore.QRect(120, 270, 101, 17))
        self.Choice_3.setObjectName("Choice_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 40, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 141, 20))
        self.label_2.setObjectName("label_2")
        self.ID_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ID_input.setGeometry(QtCore.QRect(190, 100, 141, 20))
        self.ID_input.setObjectName("ID_input")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 180, 161, 20))
        self.label_3.setObjectName("label_3")
        self.Vote_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Vote_btn.setGeometry(QtCore.QRect(20, 360, 101, 41))
        self.Vote_btn.setObjectName("Vote_btn")
        self.clear_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(200, 360, 91, 41))
        self.clear_btn.setObjectName("clear_btn")
        self.result_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(22, 430, 311, 41))
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting App"))
        self.Choice_1.setText(_translate("MainWindow", "Isabella"))
        self.Choice_2.setText(_translate("MainWindow", "Hannah"))
        self.Choice_3.setText(_translate("MainWindow", "Genji"))
        self.label.setText(_translate("MainWindow", "Vote Menu"))
        self.label_2.setText(_translate("MainWindow", "Enter your voter ID "))
        self.label_3.setText(_translate("MainWindow", "Select one Candidate"))
        self.Vote_btn.setText(_translate("MainWindow", "Vote"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
